### ISSUE TITLE
Failed to download torrent,  Reason: "expected value (list, dict, int or string) in bencoded string"

### ISSUE THREAD

**Issue by Hunter54** [victorBuzdugan/QbittorrentFilelistSearchPlugin#3]
Installing the plugin worked as expected, and i can search the torrents. 

However, when i try to download a torrent from the search results, it does nothing and qBt reports these logs:

>  Downloading torrent, please wait... Source: "https://filelist.io/download.php?id=837829"
>  Failed to load torrent. Reason: "expected value (list, dict, int or string) in bencoded string"

Any idea how to fix this?
Downloading torrents manually from the .torrent file works as expected. 

Not sure if it's even related to the plugin, but it doesn't happen with other trackers search plugins.

**Comment by victorBuzdugan** [comment]
I can’t replicate this behaviour.
Try having a look at _filelist.log_ file which can be found:

- Windows: %localappdata%\qBittorrent\nova3\engines\

- Mac: ~/Library/Application Support/qBittorrent/nova3/engines

**Comment by Hunter54** [comment]
Nothing related to this issue there. Only logs are for search results. 

> 08.09 09:37:57 DEBUG    Searching for "extraction+2" in category "all"
> 08.09 09:37:57 DEBUG    Requesting page number 0
> 08.09 09:37:57 DEBUG    Encoded url: https://filelist.io/browse.php?search=extraction+2&cat=0&searchin=1&sort=5&page=0
> 08.09 09:37:57 DEBUG    GET data from https://filelist.io/browse.php?search=extraction+2&cat=0&searchin=1&sort=5&page=0 with decode = True
> 08.09 09:37:57 DEBUG    Response status: 200
> 08.09 09:37:57 DEBUG    Returned url decoded as string.
> 08.09 09:37:57 INFO     Accessed results page.
> 08.09 09:37:57 DEBUG    Torrent size: 4.92 GB
> 08.09 09:37:57 DEBUG    Could not retrieve number of leechers. Setting 0.
> 08.09 09:37:57 INFO     Sending to prettyPrinter: https://filelist.io/download.php?id=837829|Extraction.2.2023.1080p.NF.WEB-DL.DDP5.1.Atmos.H.264-FLUX|597|4.92 GB|0|https://filelist.io|https://filelist.io/details.php?id=837829|

**Comment by victorBuzdugan** [comment]
There should be 5 parsed torrents:
08.09 12:42:11 DEBUG    Searching for "extraction+2" in category "all"
08.09 12:42:11 DEBUG    Requesting page number 0
08.09 12:42:11 DEBUG    Encoded url: https://filelist.io/browse.php?search=extraction+2&cat=0&searchin=1&sort=5&page=0
08.09 12:42:11 DEBUG    GET data from https://filelist.io/browse.php?search=extraction+2&cat=0&searchin=1&sort=5&page=0 with decode = True
08.09 12:42:11 DEBUG    Response status: 200
08.09 12:42:11 DEBUG    Returned url decoded as string.
08.09 12:42:11 INFO     Accessed results page.
08.09 12:42:11 DEBUG    Torrent size: 4.92 GB
08.09 12:42:11 DEBUG    Could not retrieve number of leechers. Setting 0.
08.09 12:42:11 INFO     Sending to prettyPrinter: https://filelist.io/download.php?id=837829|Extraction.2.2023.1080p.NF.WEB-DL.DDP5.1.Atmos.H.264-FLUX|698|4.92 GB|0|https://filelist.io|https://filelist.io/details.php?id=837829|
08.09 12:42:11 DEBUG    Torrent size: 2.03 GB
08.09 12:42:11 INFO     Sending to prettyPrinter: https://filelist.io/download.php?id=837831|Extraction.2.2023.720p.NF.WEB-DL.DDP5.1.Atmos.H.264-CMRG|262|2.03 GB|1|https://filelist.io|https://filelist.io/details.php?id=837831|
08.09 12:42:11 DEBUG    Torrent size: 10.70 GB
08.09 12:42:11 INFO     Sending to prettyPrinter: https://filelist.io/download.php?id=837882|Extraction.2.2023.2160p.NF.WEB-DL.DDP5.1.Atmos.H.265-HONE|91|10.70 GB|1|https://filelist.io|https://filelist.io/details.php?id=837882|
08.09 12:42:11 DEBUG    Torrent size: 17.09 GB
08.09 12:42:11 DEBUG    Could not retrieve number of leechers. Setting 0.
08.09 12:42:11 INFO     Sending to prettyPrinter: https://filelist.io/download.php?id=842967|Extraction.2.2023.Hybrid.2160p.NF.WEB-DL.DDP5.1.Atmos.DoVi.HDR.H.265-HONE|50|17.09 GB|0|https://filelist.io|https://filelist.io/details.php?id=842967|
08.09 12:42:11 DEBUG    Torrent size: 421.82 MB
08.09 12:42:11 DEBUG    Could not retrieve number of seeders. Setting 0.
08.09 12:42:11 DEBUG    Could not retrieve number of leechers. Setting 0.
08.09 12:42:11 INFO     Sending to prettyPrinter: https://filelist.io/download.php?id=548211|VA-Ambient.Extractions.Volume.2-CS8528-2-CD-FLAC-1996-dL|0|421.82 MB|0|https://filelist.io|https://filelist.io/details.php?id=548211|
08.09 12:42:11 INFO     Parsed 5 torrents.

**Comment by victorBuzdugan** [comment]
When downloading, the plugin creates a temporary file that is feeded to qBittorrent:
08.09 12:52:02 DEBUG    GET data from https://filelist.io/download.php?id=837829 with decode = False
08.09 12:52:03 DEBUG    Response status: 200
08.09 12:52:03 DEBUG    Returned url raw as bytes.
08.09 12:52:03 INFO     Returned to qBittorrent:"/var/folders/df/_4wtjsn975xbwrl18p_m15740000gn/T/tmpl7d6jtut.torrent https://filelist.io/download.php?id=837829"

Just an ideea: Maybe qBittorrent or python doesn't have the permission to create/delete a file...
Check _filelist.log_ file after you click download.

**Comment by Hunter54** [comment]
This is the whole log fie, i truncated it at first since i saw nothing relevant to the download process. 

> 08.09 12:58:36 DEBUG    Credentials file not found. Using data from current file.
> 08.09 12:58:36 DEBUG    New filelist object created.
> 08.09 12:58:36 DEBUG    GET data from https://filelist.io/login.php with decode = True
> 08.09 12:58:36 DEBUG    Response status: 200
> 08.09 12:58:36 DEBUG    Returned url decoded as string.
> 08.09 12:58:36 DEBUG    Retrieved validator key.
> 08.09 12:58:36 DEBUG    Cookie is in the jar.
> 08.09 12:58:36 DEBUG    POST data to https://filelist.io/takelogin.php with decode = True
> 08.09 12:58:37 DEBUG    Response status: 200
> 08.09 12:58:37 DEBUG    Returned url decoded as string.
> 08.09 12:58:37 INFO     Logged in.
> 08.09 12:58:37 DEBUG    Searching for "extraction+2" in category "all"
> 08.09 12:58:37 DEBUG    Requesting page number 0
> 08.09 12:58:37 DEBUG    Encoded url: https://filelist.io/browse.php?search=extraction+2&cat=0&searchin=1&sort=5&page=0
> 08.09 12:58:37 DEBUG    GET data from https://filelist.io/browse.php?search=extraction+2&cat=0&searchin=1&sort=5&page=0 with decode = True
> 08.09 12:58:37 DEBUG    Response status: 200
> 08.09 12:58:37 DEBUG    Returned url decoded as string.
> 08.09 12:58:37 INFO     Accessed results page.
> 08.09 12:58:37 DEBUG    Torrent size: 4.92 GB
> 08.09 12:58:37 DEBUG    Could not retrieve number of leechers. Setting 0.
> 08.09 12:58:37 INFO     Sending to prettyPrinter: https://filelist.io/download.php?id=837829|Extraction.2.2023.1080p.NF.WEB-DL.DDP5.1.Atmos.H.264-FLUX|715|4.92 GB|0|https://filelist.io|https://filelist.io/details.php?id=837829|
> 08.09 12:58:37 DEBUG    Torrent size: 2.03 GB
> 08.09 12:58:37 INFO     Sending to prettyPrinter: https://filelist.io/download.php?id=837831|Extraction.2.2023.720p.NF.WEB-DL.DDP5.1.Atmos.H.264-CMRG|268|2.03 GB|1|https://filelist.io|https://filelist.io/details.php?id=837831|
> 08.09 12:58:37 DEBUG    Torrent size: 10.70 GB
> 08.09 12:58:37 INFO     Sending to prettyPrinter: https://filelist.io/download.php?id=837882|Extraction.2.2023.2160p.NF.WEB-DL.DDP5.1.Atmos.H.265-HONE|93|10.70 GB|1|https://filelist.io|https://filelist.io/details.php?id=837882|
> 08.09 12:58:37 DEBUG    Torrent size: 17.09 GB
> 08.09 12:58:37 DEBUG    Could not retrieve number of leechers. Setting 0.
> 08.09 12:58:37 INFO     Sending to prettyPrinter: https://filelist.io/download.php?id=842967|Extraction.2.2023.Hybrid.2160p.NF.WEB-DL.DDP5.1.Atmos.DoVi.HDR.H.265-HONE|50|17.09 GB|0|https://filelist.io|https://filelist.io/details.php?id=842967|
> 08.09 12:58:37 DEBUG    Torrent size: 421.82 MB
> 08.09 12:58:37 DEBUG    Could not retrieve number of seeders. Setting 0.
> 08.09 12:58:37 DEBUG    Could not retrieve number of leechers. Setting 0.
> 08.09 12:58:37 INFO     Sending to prettyPrinter: https://filelist.io/download.php?id=548211|VA-Ambient.Extractions.Volume.2-CS8528-2-CD-FLAC-1996-dL|0|421.82 MB|0|https://filelist.io|https://filelist.io/details.php?id=548211|
> 08.09 12:58:37 INFO     Parsed 5 torrents.

And this is what appears in the qbittorrent.log file

> 
> (N) 2023-09-08T12:58:09 - WebAPI login success. IP: ::ffff:172.17.0.1
> (N) 2023-09-08T12:58:16 - WebAPI login success. IP: ::ffff:172.17.0.1
> (N) 2023-09-08T12:58:28 - WebAPI login success. IP: ::ffff:172.17.0.1
> (N) 2023-09-08T12:59:17 - Downloading torrent, please wait... Source: "https://filelist.io/download.php?id=837829"
> (W) 2023-09-08T12:59:18 - Failed to load torrent. Reason: "expected value (list, dict, int or string) in bencoded string"

There is no mention of the download from your log file. 
Can you tell me the path where the file should be downloaded? The logs are taken from a qbittorrent docker container, so maybe this could be the issue.

**Comment by victorBuzdugan** [comment]
So clearly, as you said, search works and parses the correct number of torrents.
If the _filelist.log_ file doesn't update with the data I provided in my last post, it doesn't create a temp file. I'm guessing the download method from the filelist plugin isn't even called. If it was requested there should be something in the log file either "Returned to qBittorrent:"[link_to_temporary_file]" or "Cannot acces download torrent url!" or some other error... but something should be there.
The temp file folder is different for every system. The script only requests from the operating system a temp file location and the OS decides where to put the file and returns the path to the script.

**Comment by Hunter54** [comment]
Yeah. I don't really know. 

Other search plugins for public trackers work as expected, only filelist does this. 
Probably something to do with the WebUI and this search plugin. 
I'll maybe try to debug it myself if i got the time to learn how qBt plugins work.
