### ISSUE TITLE
search is working but torrents are not being downloaded

### ISSUE THREAD

**Issue by fborangic** [victorBuzdugan/QbittorrentFilelistSearchPlugin#4]
![image](https://github.com/victorBuzdugan/QbittorrentFilelistSearchPlugin/assets/33522552/3d65bf0a-0218-4b44-bf8c-6e01db0f09c5)

qBittorrent v4.6.2 Web UI (64-bit)
running it in a linux/docker environment.
---
version: "2.1"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
      - WEBUI_PORT=8080
    volumes:
      - /localpath:/config
      - /localpath:/downloads
    ports:
      - 8080:8080
      - 192.168.101.10:6881:6881
      - 192.168.101.10:6881:6881/udp
      
    restart: unless-stopped
    network_mode: host

I can gather more information on this upon request. Not sure what is needed to troubleshoot this further.

**Comment by fborangic** [comment]
[filelist.log](https://github.com/victorBuzdugan/QbittorrentFilelistSearchPlugin/files/13697222/filelist.log)

**Comment by victorBuzdugan** [comment]
Hi,
This looks very similar to issue #3 which, unfortunately, I couldn't replicate or fix.
